services:
  postgres:
    image: postgres
    ports:
      # trunk-ignore(yamllint/quoted-strings)
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
